### ISSUE TITLE
Swift build produces no output

### ISSUE THREAD

**Issue by haze** [mitsuse/swim#5]
Swift version:
```
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.3.0
```
After running `swift build -c release` no output (files / folders) were found in the working directory.

Running with the verbose (`-v`) flag shows these commands:
```
xcrun --sdk macosx --show-sdk-path
xcrun --sdk macosx --show-sdk-platform-path
xcrun --sdk macosx --find xctest
```

Any ideas?

**Comment by mitsuse** [comment]
@haze Please check whether `.build/release/swim`  exists or not.

**Comment by haze** [comment]
@mitsuse the `.build` folder didn't exist before, but I deleted the root folder & re-cloned and it worked. Thanks!
